CREATE TABLE PRODUCT (
	product_id BIGINT NOT NULL AUTO_INCREMENT,
	product_name VARCHAR (150) NOT NULL,
	PRIMARY KEY (product_id)
) ENGINE=InnoDB;

CREATE TABLE REVIEW (
	review_id BIGINT NOT NULL AUTO_INCREMENT,
	review VARCHAR (255) NOT NULL,
	product_id BIGINT,
	PRIMARY KEY (review_id),
	CONSTRAINT product_fk FOREIGN KEY (product_id) REFERENCES PRODUCT(product_id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE COMMENT (
	comment_id BIGINT NOT NULL AUTO_INCREMENT,
	comment VARCHAR (255) NOT NULL,
	review_id BIGINT,
	PRIMARY KEY (comment_id),
	CONSTRAINT comment_fk FOREIGN KEY (review_id) REFERENCES REVIEW(review_id) ON DELETE CASCADE
);